error_page 400 /npm_error_pages/400.html
error_page 401 /npm_error_pages/401.html
error_page 403 /npm_error_pages/403.html
error_page 404 /npm_error_pages/404.html
error_page 500 /npm_error_pages/500.html
error_page 502 /npm_error_pages/502.html
error_page 503 /npm_error_pages/503.html

location /npm_error_pages {
  root /data/error_pages;
}
